# Generated by Django 6.0.2 on 2026-03-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='token_paydunya',
            new_name='reference_paiement',
        ),
    ]
