# Generated by Django 6.0.3 on 2026-03-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_principale', models.ImageField(upload_to='tableaux/')),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tableau',
                'verbose_name_plural': 'Tableaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoRealisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='catalogue.tableau')),
            ],
            options={
                'verbose_name': 'Photo de réalisation',
                'verbose_name_plural': 'Photos de réalisation',
                'ordering': ['ordre'],
            },
        ),
    ]
