# Generated by Django 6.0.3 on 2026-03-14 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom_client', models.CharField(max_length=200)),
                ('numero_whatsapp', models.CharField(max_length=20)),
                ('pseudo_whatsapp', models.CharField(blank=True, max_length=200)),
                ('nb_unites', models.PositiveIntegerField(default=1)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_avance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_solde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE_AVANCE', 'Payée avance'), ('EN_PRODUCTION', 'En production'), ('PRETE', 'Prête'), ('RETRAIT_EN_COURS', 'Retrait en cours'), ('SOLDEE', 'Soldée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tableau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='catalogue.tableau')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commandes/photos/')),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Photo commande',
                'verbose_name_plural': 'Photos commande',
            },
        ),
    ]
